### ISSUE TITLE
changing setting for what directory to move finished file to.

### ISSUE THREAD

**Issue by reflexwolf** [gazpachoking/deluge-autoadd-plugin#8]
The addon is changing the directory that the torrent is moved to after finished from what I have in my settings to /user/me (me=my name) it took quite a while to figure out why the finished files where not where they should be, and where they went.

**Comment by gazpachoking** [comment]
You can set the move completed folder per autoadd directory. Sounds like you just need to uncheck that option for yours if you want to leave it at default move completed directory.

**Comment by reflexwolf** [comment]
Thank you so very much I found the setting and was able to fix the problem!
